### ISSUE TITLE
env is what??

### ISSUE THREAD

**Issue by zdx3578** [elggem/ae-destin#7]
which version: tensorlfow? python? ubuntu? ros?

**Comment by zdx3578** [comment]
new latst tf :  pip install tf ;
error:

creating node @ level 2
  registering region @ 0 0
Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/tensorflow_node/scripts/daemon", line 35, in <module>
    architecture = architecture_class(sess, inputlayer, **architecture_params)
  File "/home/ubuntu/catkin_ws/src/tensorflow_node/src/tensorflow_node/architectures/destin.py", line 50, in __init__
    destin_node(0, nr_of_layers)
  File "/home/ubuntu/catkin_ws/src/tensorflow_node/src/tensorflow_node/architectures/destin.py", line 30, in destin_node
    node.register_tensor(destin_node(level + 1, number_of_layers, x_pos, y_pos))
  File "/home/ubuntu/catkin_ws/src/tensorflow_node/src/tensorflow_node/architectures/destin.py", line 30, in destin_node
    node.register_tensor(destin_node(level + 1, number_of_layers, x_pos, y_pos))
  File "/home/ubuntu/catkin_ws/src/tensorflow_node/src/tensorflow_node/architectures/destin.py", line 39, in destin_node
    node.initialize_graph()
  File "/home/ubuntu/catkin_ws/src/tensorflow_node/src/tensorflow_node/nodes/autoencoder.py", line 77, in initialize_graph
    input_concat = tf.concat(1, self.input_tensors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

my env:
python 2.7  ros indigo ubuntu 1404

**Comment by elggem** [comment]
Hey!

Environment seems fine, but master branch is not updated for TF 1.0. Try the gan branch qnd possibly TF 1.0 not 1.1.0.

**Comment by elggem** [comment]
Dont use the development branch. I've been meaning to merge gan back to master and clean up but haven't come around to it yet!

**Comment by zdx3578** [comment]
which your  python version?

which your  ubuntu version?

which your  ros version ?

**Comment by elggem** [comment]
Hi, your environment seems fine, I have it running on Python 2.7.6, Ubuntu 14.04 and ROS Indigo. Did you try the 'gan' branch and are you running from a ROS workspace?

**Comment by zdx3578** [comment]
thanks ,i will try.
